
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /cupprintAccounts

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore "./cupprintAccounts/cupprintAccounts.csproj" --disable parallel
# Build and publish a release
RUN dotnet publish "./cupprintAccounts/cupprintAccounts.csproj" -c -release -o /app --no-restore

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/out .
EXPOSE 5000
ENTRYPOINT ["dotnet", "cupprintAccounts.dll"]